### ISSUE TITLE
Register B3

### ISSUE THREAD

**Issue by SergeyKanzhelev** [w3c/tracestate-ids-registry#2]
B3 seems to have some document: https://cwiki.apache.org/confluence/display/ZIPKIN/b3+single+header+format

Reporting as a regular issue for now to keep track of it. Later may need to go thru the process proposed in #1

**Comment by codefromthecrypt** [comment]
It should be "b3" not "B3" and the correct tentative link is here https://github.com/openzipkin/b3-propagation#single-header

once there's practice in https://github.com/openzipkin-contrib/brave-propagation-w3c, we'll update a section on the semantics. The main idea is that you can stash the complete contents of "b3" single format, and recognize that this allows propagation of sampling only `b3=1`. When "b3" entry is present, traceparent is ignored as it could have an fake trace ID/span ID due to gaps in the spec which don't know what to do when tracestate precedes a sampled trace.

cc @anuraaga @narayaruna @jcchavezs @jeqo @basvanbeek

**Comment by codefromthecrypt** [comment]
one of the problems of this registry is that it is implying there's a conflation between a data format and a system. For example, "b3" would be a format and a possible indication of a system if there's only one system involved. This is different than it would be for something like "xray" where there may be an implied global system that also has the same format.

In other words, I would suggest thinking about the difference between an anonymous instance of a format vs potentially multiple instances of things that use the same format.

For example, you could imagine 2 instances of the "b3" format, with different keys. There's probably text needed to suggest a "provider" ex something expected to have a single namespace over the internet. vs  a format which might be used by multiple systems in even the same network.

**Comment by SergeyKanzhelev** [comment]
> one of the problems of this registry is that it is implying there's a conflation between a data format and a system. For example, "b3" would be a format and a possible indication of a system if there's only one system involved. This is different than it would be for something like "xray" where there may be an implied global system that also has the same format.

Yes, this is clearly a problem. Any attempt to interpret the last `tracestate` entry as a specific monitoring system is faulty. I am still not convinced we need this registry, but I see a value in claiming the entry to avoid unnecessary conflicts. We already changed this registry by removing column that refers to a spec how that entry is used and its semantic. Which is another step to move from being a specification that enables better cooperation to being just a list.

**Comment by basti1302** [comment]
@SergeyKanzhelev this seems to be stale, and there also seems to be little interest, can we close this?
